import type { Metadata } from "next";
import { Source_Sans_3, Manrope } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { siteDetails } from '@/data/site-details';

import "./globals.css";

const manrope = Manrope({ subsets: ['latin'] });
const sourceSans = Source_Sans_3({ subsets: ['latin'] });

const { metadata: meta, siteUrl } = siteDetails;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: meta.title,
    template: `%s | ${siteDetails.siteName}`,
  },
  description: meta.description,
  keywords: meta.keywords?.join(', '),
  authors: [{ name: siteDetails.siteName, url: siteUrl }],
  creator: siteDetails.siteName,
  publisher: siteDetails.siteName,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
  openGraph: {
    title: meta.title,
    description: meta.description,
    url: siteUrl,
    siteName: siteDetails.siteName,
    type: 'website',
    locale: siteDetails.locale,
    // OG image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: meta.title,
    description: meta.description,
  },
  alternates: {
    canonical: siteUrl,
  },
  category: 'pets',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${sourceSans.className} antialiased`}
        suppressHydrationWarning
      >
        <Header />
        <main className="pt-16 md:pt-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
